# Generated by Django 3.1.3 on 2020-11-29 15:08

from django.db import migrations, models
import django.db.models.deletion
import todo_app.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaTarefas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_lista', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300)),
                ('data_criacao', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, 'CONCLUIDA'), (2, 'NAO_CONCLUIDA')], default=todo_app.utils.StatusTarefa['NAO_CONCLUIDA'])),
                ('lista_tarefas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo_app.listatarefas')),
            ],
        ),
    ]
